# fly.toml app configuration file generated for swiflow-auth on 2025-08-26T11:29:17+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'swiflow-auth'
primary_region = 'hkg'

[build]
  image = 'docker.io/optltd/llm-member:latest'

[env]
  APP_MODE = 'test'
  APP_PORT = '8080'
  APP_NAME = 'Swiflow'
  AUTH_CALLBACK = 'swiflow://auth'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1g'
  cpu_kind = 'shared'
  cpus = 1
